import type { Metadata } from 'next';
import {
    Cormorant_Garamond,
    Geist,
    Geist_Mono,
    Rampart_One,
} from 'next/font/google';
import './globals.css';

const cormorantGaramond = Cormorant_Garamond({
    subsets: ['latin', 'cyrillic'],
    weight: ['400', '600', '700'],
    variable: '--font-cormorant',
    display: 'swap',
});

const rampartOne = Rampart_One({
    subsets: ['latin', 'cyrillic'],
    weight: ['400'],
    variable: '--font-rampart-one',
    display: 'swap',
});

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: LayoutProps<'/'>) {
    return (
        <html
            lang="en"
            className={`${geistSans.variable} ${geistMono.variable} ${cormorantGaramond.variable} ${rampartOne.variable} h-full antialiased`}
        >
            <body className="min-h-full flex flex-col">{children}</body>
        </html>
    );
}
